export const ACTIVATE_EFFECT = 'ACTIVATE_EFFECT';
export const PLAYER_CHECK_SELF = 'PLAYER_CHECK_SELF';
export const PLAYER_CHECK_OTHER = 'PLAYER_CHECK_OTHER';
export const CHOOSE_CARD = 'CHOOSE_CARD';
